name: Developer Tests

on: push

jobs:
  launch-tests:
    runs-on: ubuntu-latest
    container: openjdk:8-jdk-alpine

    steps:
      - uses: actions/checkout@v1

      # Instalar Maven y dependencias necesarias
      - name: Install Maven
        run: |
          apk update
          apk add maven

      # Ejecutar tests
      - name: Launch tests with Maven
        run: ./mvnw test